#!/bin/bash
# This script builds the tags for use when doing
# development on the compiler or on a user-project.
echo "$0"
tags_file="./tags"

function maybe-dir {
	[[ -d $1 ]] && echo $1
}

if [ $# -eq 0 ]; then
  targets=(
    .
    "$(maybe-dir "$(llvm-config --cppflags | xargs -n 1 echo | grep '^-I' | cut -c3-)")"
    "${CIDER_ROOT:-/usr/local/share/cider}"
  )
else
  targets=(
    "$*"
  )
fi

echo "targets=(${targets[*]})"
ztags=/var/tmp/ztags
rm -f "$ztags"

trap 'rm -f "$ztags"' EXIT

# shellcheck disable=SC2068
ctags -f "$tags_file" -R ${targets[@]} || exit 1

gather-cider-tags() {
  keyword=$1
  code=$2
  allow_indent=$3
  spacePlus="[[:space:]]+"
  if [ -n "$allow_indent" ]; then
    indent="[[:space:]]*"
  else
    indent=""
  fi
  # shellcheck disable=SC2068
  for target in ${targets[@]}; do
    # shellcheck disable=SC2038
    find -L "$target" -regex '.*\.cider$' \
      | xargs grep -ERn "^$indent$keyword$spacePlus.*" \
      | sed \
        -Ene \
        's/^([^:]+):([^:]+):('"$indent$keyword$spacePlus"'([a-zA-Z0-9_]+).*)$/\4	\1	\/^\3$\/;"	'"$code"'/p' \
      >> "$ztags"
  done
}

gather-cider-tags "let" "v"
gather-cider-tags "fn" "f" 1
gather-cider-tags "class" "s"
gather-cider-tags "instance" "s"
gather-cider-tags "newtype" "s"
gather-cider-tags "struct" "s"
# TODO: support data-ctors

cat "$tags_file" >> "$ztags"
sort "$ztags" > "$tags_file"
rm "$ztags"
wc -l "$tags_file"
# cat "$tags_file" | grep -Ev '^!' | awk '{ print $2 }' | xargs -n 1 dirname 2>/dev/null | sort | uniq -c | sort -rn
