#!/bin/bash
# Note this assumes CIDER_SRC_DIR is $HOME/src/cider.
CIDER_SRC_DIR="${CIDER_SRC_DIR:-$PWD}"
CIDER_ROOT="${CIDER_ROOT:-/usr/local/share/cider}"

cd "$CIDER_ROOT" || { printf "Couldn't cd into %s.\n" "$CIDER_ROOT"; exit 1; }
rm -rf runtime
rm -rf lib
ln -s "$CIDER_SRC_DIR/runtime" .
ln -s "$CIDER_SRC_DIR/lib" .
