#!/bin/bash
# This script builds the tags for use when doing
# development on the compiler or on a user-project.
tags_file="./tags"

if [ $# -eq 0 ]; then
  targets=(
    .
    "$ZION_ROOT"
  )
else
  targets=(
    "$*"
  )
fi

ztags=/var/tmp/ztags
rm -f "$ztags"

trap 'rm -f "$ztags"' EXIT

# shellcheck disable=SC2068
ctags -f "$tags_file" -R ${targets[@]} || exit 1

gather-zion-tags() {
  keyword=$1
  code=$2
  allow_indent=$3
  spacePlus="[[:space:]]+"
  if [ -n "$allow_indent" ]; then
    indent="[[:space:]]*"
  else
    indent=""
  fi
  # shellcheck disable=SC2068
  for target in ${targets[@]}; do
    # shellcheck disable=SC2038
    find "$target" -regex '.*\.zion$' \
      | xargs grep -ERn "^$indent$keyword$spacePlus.*" \
      | sed \
        -Ene \
        's/^([^:]+):([^:]+):('"$indent$keyword$spacePlus"'([a-zA-Z0-9_]+).*)$/\4	\1	\/^\3$\/;"	'"$code"'/p' \
      >> "$ztags"
  done
}

gather-zion-tags "let" "v"
gather-zion-tags "fn" "f" 1
gather-zion-tags "class" "s"
gather-zion-tags "instance" "s"
gather-zion-tags "newtype" "s"
gather-zion-tags "struct" "s"

cat "$tags_file" >> "$ztags"
sort "$ztags" > "$tags_file"
rm "$ztags"
