.TH ZION 1
.SH NAME
zion \- Zion programming language compiler
.SH SYNOPSIS
zion [\fIprogram\fR] [\fIargs\fR ...]
.br
zion [\fBrun\fR \fIprogram\fR] [\fIargs\fR ...]
.br
zion [\fBfind\fR \fIprogram\fR]
.br
zion [\fBlex\fR \fIprogram\fR]
.br
zion [\fBparse\fR \fIprogram\fR]
.br
zion [\fBcompile\fR \fIprogram\fR]
.br
zion [\fBspecialize\fR \fIprogram\fR]
.br
zion [\fBll\fR \fIprogram\fR]
.br
zion [\fBtest\fR] \-\- run unit tests
.SH DESCRIPTION
.na
Zion is a general purpose programming language.
The source code is available at \fBhttps://github.com/zionlang/zion\fR.
.P
zion
.B run
will attempt to compose all the phases of compilation, then pass the resulting LLVM code off to
.B clang
to lower it down to machine code and create the final executable binary.
It will then
.B execvp
the built user program and pass along any remaining \fIargs\fR.
.br
.P
zion
.B ll
will emit an LLVM IR file of the
.I program
and its dependencies.
.P
.I program
is resolved by
.B zion
into an actual filename.
When you reference a source file, you can omit the `.zion` extension.
When searching for the specified \fIprogram\fR, \fBzion\fR will look in the current directory first, then proceed to looking through the \fBZION_PATH\fR, as described below.
.SH ENVIRONMENT
.TP
.br
ZION_ROOT=\fI/usr/local/share/zion\fR
Should point to the base directory for standard runtime and library.
If 
.B ZION_PATH
is not set, it will default to
.B $ZION_ROOT/lib
\&. If 
.B ZION_RUNTIME
is not set, it will default to "
.B $ZION_ROOT/runtime
\&.
.TP
.br
ZION_PATH=\fI/usr/local/share/zion/lib\fR
A colon-separated list of directories to search for imported libraries.
Libraries are imported with the `import` keyword.
The `lib/std.zion` library is called the prelude and is automatically imported unless 
.B NO_PRELUDE
is given. Setting this variable overrides the
.B $ZION_ROOT/lib
location.
.TP
.br
ZION_RUNTIME=\fI/usr/local/share/zion/runtime\fR
The location of the C-runtime portion of Zion's builtins. See src/zion_rt.c. Setting this variable overrides the
.B $ZION_ROOT/runtime
location.
.TP
.br
NO_PRELUDE=\fI1\fR
Prevents the automatic import of the `std` library.
This is generally not useful since the language is tied to the runtime library in a few ways.
It comes in handy for writing tests of the compiler itself.
.TP
.br
DEBUG=\fI[0-10]\fR
Sets the level of debugging information to spew.
Default is 0 or none.
Note that
.B zion
must be compiled with
.B \-DZION_DEBUG
in order to enable debug logging.
See src/logging.cpp.
.TP
.br
STATUS_BREAK=\fI1\fR
When set to non-zero value,
.B zion
breaks into the debugger at the first user error found (helpful when working on the compiler).
.TP
.br
DUMP_BUILTINS=\fI1\fR
When set to non-zero value,
.B zion
lists all the registered builtin functions and quits.
.SH LICENSE
.sp
Zion Programming Environment
.TP
.br
MIT License
.TP
.br
Copyright (c) 2019 William Bradley
.TP
.br
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:
.TP
.br
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.TP
.br
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
.SH "REPORTING BUGS"
.sp
Note that Zion is still a pre-release language/compiler. Bug reports are greatly appreciated. Report bugs to the Zion GitHub site. \fBhttps://github.com/zionlang/zion/issues\fR.
